channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=25.1
- pip:
  - mlflow==2.22.0
  - numpy==2.2.6
  - pandas==2.3.0
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.15.2
  - xgboost==3.0.2
name: mlflow-env
